export const GET_SUBCATEGORIESS_REQUEST = 'GET_SUBCATEGORIESS_REQUEST';
export const GET_SUBCATEGORIESS_SUCCESS = 'GET_SUBCATEGORIESS_SUCCESS';
export const GET_SUBCATEGORIESS_FAIL = 'GET_SUBCATEGORIESS_FAIL';